name: Automerge

on:
    workflow_call:

jobs:
    merge:
        name: automerge
        runs-on: ubuntu-latest
        steps:
            - id: automerge
              name: automerge
              uses: "pascalgn/automerge-action@v0.16.3"
              with:
                labels: automerge
              env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                #MERGE_LABELS: "automerge"
                MERGE_REMOVE_LABELS: ""
                MERGE_METHOD: "squash"
                MERGE_COMMIT_MESSAGE: "automerge"
                MERGE_FORKS: "true"
                MERGE_RETRIES: "1"
                MERGE_RETRY_SLEEP: "1000"
                MERGE_REQUIRED_APPROVALS: "0"
                UPDATE_LABELS: ""
                UPDATE_METHOD: "rebase"
                BASE_BRANCHES: "main"

            ##Automerge confirmation message
            - name: feedback
              if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
              run: |
                echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
