name: pipeline

on: [push]

jobs:
  analysis:
    name: Analysis
    uses: ./.github/workflows/analysis.yml
    
  ##This section will made the auto merge.
  merge:
    name: Merge Phase
    needs: [analysis]
    #This "if" will be the validator about security before the branch would be merge
    ##if: contains(github.event.head_commit.message, 'PRUEB')
    uses: ./.github/workflows/merge.yml
