name: pipeline

on:
  pull_request:
    types: [opened]

jobs:
  analysis:
    name: Analysis
    uses: ./.github/workflows/analysis.yml
    
  ##This section will made the auto merge.
  merge:
    name: Merge Phase
    needs: [analysis]
    #This "if" will be the validator about security before the branch would be merge
    if: ${{ github.event.label.name == 'automerge' }}
    uses: ./.github/workflows/merge.yml
